# MODULES (EXTERNAL)
# ---------------------------------------------------------------------------------------------------------------------
import os, contextlib
from typing import Generator, Any
# ---------------------------------------------------------------------------------------------------------------------

# MODULES (INTERNAL)
# ---------------------------------------------------------------------------------------------------------------------
# Get listed here!
# ---------------------------------------------------------------------------------------------------------------------

# OPERATIONS / CLASS CREATION / GENERAL FUNCTIONS
# ---------------------------------------------------------------------------------------------------------------------

@contextlib.contextmanager
def suppress_native_output() ->  Generator[None, Any, None]:
    """
    Context manager that temporarily suppresses standard output (stdout) and error output (stderr) 
    at the operating system level.

    This mechanism is specifically designed to silence messages generated by native libraries written 
    in C/C++, in this case MediaPipe and TensorFlow Lite, which write directly to the process's *file
    descriptors* (FD 1 and FD 2) and do not respect the logging systems configurable from Python.

    **Problem solved:** Some libraries used in this project generate informational messages and warnings 
    directly from their native backend. This can cause conflicts with the application's own messages.

    **These messages:**
        - Cannot be silenced using os.environ.
        - Cannot be captured with sys.stderr.
        - Do not respond to contextlib.redirect_stderr.

    **Internal operation:**
        - A copy of the original process descriptors is saved:
            * FD 1 → stdout.
            * FD 2 → stderr.
        - Both descriptors are temporarily redirected to the system's null device (os.devnull).
        - The protected block is executed within the context.
        - The original descriptors are restored to ensure that the rest of the program functions normally.

    **Important warning:** During the execution of this context, **all** native output is suppressed, 
    including any critical error messages generated by C/C++ code. For this reason, its use should be 
    limited to well-controlled sections of the code.

    Yields:
        Generator:
            None

    ### Its use as a global wrapper for the entire application is not recommended.
    """
    #1 = stdout (standard output)
    #2 = stderr (standard error output)
    null_fd = os.open(os.devnull, os.O_WRONLY)

    # Save the original process descriptors
    saved_stdout = os.dup(1)
    saved_stderr = os.dup(2)

    try:
        # Redirect stdout and stderr to the null device
        os.dup2(null_fd, 1)
        os.dup2(null_fd, 2)
        yield
    finally:
        # Restore the original process descriptors
        os.dup2(saved_stdout, 1)
        os.dup2(saved_stderr, 2)

        # Close the temporary descriptors
        os.close(saved_stdout)
        os.close(saved_stderr)
        os.close(null_fd)

# ---------------------------------------------------------------------------------------------------------------------
# END OF FILE